import type { BadgeId } from "./badges";
import type { DisciplineId, Software } from "./disciplines";
import { DISCIPLINE_TO_PROFESSION, getProfession, type Profession } from "./professions";
import { tierForPercentile, type TierId } from "./tiers";

export type Availability = "available" | "open" | "on-mission" | "unavailable" | "hired";
export type WorkMode = "remote" | "onsite" | "hybrid";
export type ContractType = "freelance" | "fulltime" | "studio" | "any";

export interface PortfolioItem {
  id: string;
  kind: "image" | "video";
  title: string;
  subtitle?: string;
  gradient: string;
  ratio?: "16/9" | "4/5" | "1/1";
}

export interface Experience {
  studio: string;
  role: string;
  period: string;
  detail?: string;
}

export interface Talent {
  id: string;
  slug: string;
  name: string;
  handle: string;
  initials: string;
  /** Country code where the talent currently lives (residence). */
  countryCode: string;
  /** Optional ISO code of the talent's nationality (citizenship).
   *  Falls back to `countryCode` when undefined. */
  nationalityCode?: string;
  city?: string;
  /** Legacy creative discipline. Kept for backward compatibility — new profiles use `professionId`. */
  discipline: DisciplineId;
  /** New cross-sector profession slug (matches lib/professions.ts). */
  professionId?: string;
  specialties: string[];
  yearsExperience: number;
  software: Software[];
  languages: string[];
  workMode: WorkMode;
  contractType: ContractType;
  availability: Availability;
  availabilityNote?: string;
  /** Sprint 2 vision: extended availability modes. */
  freelanceOnly?: boolean;
  remoteOnly?: boolean;
  availableInDays?: number;
  bio: string;
  tagline: string;
  showreelUrl?: string;
  links: { artstation?: string; vimeo?: string; youtube?: string; linkedin?: string; website?: string };
  portfolio: PortfolioItem[];
  experiences: Experience[];
  score: number;
  percentile: number;
  globalRank: number;
  disciplineRank: number;
  countryRank: number;
  badges: BadgeId[];
  responseHours: number;
  projects: number;
  endorsements: number;
  avatarGradient: string;
  recentlyJoined?: boolean;
  trending?: boolean;
}

// Avatar gradients — palette 100% alignée charte officielle.
//
//   • Bleus CLAIRS  → skyblue.{200..500}  (bleu vif #1E6BFF, palette charte)
//   • Bleus PROFONDS → deepblue.{500..900} (bleu logo #0A1E3F)
//   • Orange        → energy.{300..500}   (orange charte #FF8A00)
//
// Les gradients non-bleus (amber, violet, rose, emerald, lime) gardent
// leurs couleurs d'origine — la variation chromatique reste utile pour
// distinguer les talents au scroll d'un leaderboard.
const G = {
  // ─── Gradients bleus charte (clair → profond) ──────────────────────
  cyanOcean:  "from-skyblue-300 via-skyblue-500 to-deepblue-800",  // ciel vif → bleu profond
  steelBlue:  "from-skyblue-200 via-skyblue-500 to-deepblue-700",  // ciel pâle → bleu profond
  arcticCyan: "from-skyblue-100 via-skyblue-400 to-deepblue-900",  // ciel glacé → bleu profond très foncé
  brandWave:  "from-energy-400 via-skyblue-500 to-deepblue-800",   // orange → ciel → bleu (signature charte)
  // ─── Autres gradients (multi-couleur, inchangés) ────────────────────
  amberSun: "from-amber-300 via-orange-500 to-rose-800",
  violetDream: "from-violet-400 via-fuchsia-500 to-indigo-900",
  emeraldDeep: "from-emerald-300 via-teal-600 to-slate-900",
  roseDusk: "from-rose-300 via-pink-500 to-purple-900",
  goldNoir: "from-yellow-200 via-amber-500 to-zinc-900",
  magmaRed: "from-orange-400 via-red-600 to-zinc-900",
  forestMist: "from-lime-300 via-emerald-600 to-slate-900",
};

const port = (items: Array<Omit<PortfolioItem, "id">>): PortfolioItem[] =>
  items.map((p, i) => ({ ...p, id: String(i + 1) }));

export const TALENTS: Talent[] = [
  {
    id: "t-001",
    slug: "jean-onana",
    name: "Jean Marie O.",
    handle: "@jean-onana",
    initials: "JM",
    // Lives in France (Paris), Cameroonian nationality.
    countryCode: "FR",
    nationalityCode: "CM",
    city: "Paris",
    discipline: "generalist-3d",
    specialties: ["Character Animation", "Cinematic FX", "Look-Dev"],
    yearsExperience: 6,
    software: ["Maya", "Unreal Engine", "Substance Painter", "ZBrush", "Houdini", "Nuke"],
    languages: ["French", "English"],
    workMode: "hybrid",
    contractType: "any",
    availability: "available",
    availabilityNote: "Open to projects from June 2026",
    bio: "3D Generalist & Animator with a cinematic eye. I move between animation, lighting and FX to ship shots end-to-end.",
    tagline: "Shot-ownership generalist. Cinematic to the frame.",
    showreelUrl: "https://vimeo.com/showcase/jeanmarie",
    links: { artstation: "https://artstation.com/jeanmarie", vimeo: "https://vimeo.com/jeanmarie" },
    portfolio: port([
      { kind: "video", title: "Fauves — Title Sequence", subtitle: "Director's cut", gradient: G.amberSun, ratio: "16/9" },
      { kind: "image", title: "Coq Bleu — Concept Frame", gradient: G.cyanOcean, ratio: "16/9" },
      { kind: "image", title: "Megacity — Lookdev", gradient: G.violetDream, ratio: "4/5" },
      { kind: "image", title: "Hero Shot 042", gradient: G.steelBlue, ratio: "1/1" },
      { kind: "video", title: "Creature Run Cycle", gradient: G.emeraldDeep, ratio: "16/9" },
      { kind: "image", title: "Spec Project — Reaper", gradient: G.magmaRed, ratio: "4/5" },
    ]),
    experiences: [
      { studio: "MOPA", role: "Animation Graduate Film", period: "2022 – 2023" },
      { studio: "Ynov Paris", role: "3D Generalist (BFA)", period: "2018 – 2021" },
      { studio: "Independent / Freelance", role: "Cinematic Generalist", period: "2023 – Present" },
    ],
    score: 88,
    percentile: 7,
    globalRank: 412,
    disciplineRank: 38,
    countryRank: 1,
    badges: ["showreel-verified", "available", "visual-storytelling", "in-demand", "international"],
    responseHours: 4,
    projects: 24,
    endorsements: 19,
    avatarGradient: G.cyanOcean,
  },
  {
    id: "t-002",
    slug: "lina-park",
    name: "Lina Park",
    handle: "@linapark",
    initials: "LP",
    countryCode: "KR",
    city: "Seoul",
    discipline: "unreal",
    specialties: ["Virtual Production", "Nanite Worlds", "Real-time Lighting"],
    yearsExperience: 8,
    software: ["Unreal Engine", "Maya", "Substance Designer", "Houdini", "RealityCapture"],
    languages: ["Korean", "English"],
    workMode: "hybrid",
    contractType: "freelance",
    availability: "available",
    bio: "Virtual production specialist. I build photoreal Unreal worlds for ad and film clients.",
    tagline: "Real-time worlds, film-quality light.",
    links: { artstation: "https://artstation.com/linapark" },
    portfolio: port([
      { kind: "video", title: "Neo-Seoul — Spec Reel", gradient: G.amberSun, ratio: "16/9" },
      { kind: "image", title: "Tokyo Bay — Nanite Test", gradient: G.cyanOcean, ratio: "16/9" },
      { kind: "image", title: "Lumen Interior 03", gradient: G.goldNoir, ratio: "4/5" },
      { kind: "image", title: "Volumetric Forest", gradient: G.forestMist, ratio: "1/1" },
    ]),
    experiences: [
      { studio: "DEXTER Studios", role: "Senior Unreal Artist", period: "2021 – 2024" },
      { studio: "Locus", role: "Real-time TD", period: "2018 – 2021" },
    ],
    score: 94,
    percentile: 2,
    globalRank: 18,
    disciplineRank: 4,
    countryRank: 1,
    badges: ["unreal-specialist", "top10", "showreel-verified", "fast-responder", "available"],
    responseHours: 2,
    projects: 41,
    endorsements: 36,
    avatarGradient: G.amberSun,
  },
  {
    id: "t-003",
    slug: "kofi-mensah",
    name: "Kofi Mensah",
    handle: "@kofim",
    initials: "KM",
    countryCode: "NG",
    city: "Lagos",
    discipline: "motion-design",
    specialties: ["Brand Motion", "Type in Motion", "3D Mograph"],
    yearsExperience: 5,
    software: ["After Effects", "Cinema 4D", "Octane", "Illustrator"],
    languages: ["English", "French"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Motion designer working across brand and streaming clients.",
    tagline: "Rhythmic, type-first motion that earns the screen.",
    links: { vimeo: "https://vimeo.com/kofim" },
    portfolio: port([
      { kind: "video", title: "Spotify Africa — Ident", gradient: G.violetDream, ratio: "16/9" },
      { kind: "image", title: "Editorial Series 01", gradient: G.roseDusk, ratio: "1/1" },
      { kind: "image", title: "Type Study — Akan", gradient: G.goldNoir, ratio: "4/5" },
    ]),
    experiences: [
      { studio: "Buck", role: "Freelance Designer", period: "2023 – Present" },
      { studio: "Studio AKA", role: "Junior Motion Designer", period: "2020 – 2022" },
    ],
    score: 84,
    percentile: 9,
    globalRank: 612,
    disciplineRank: 46,
    countryRank: 1,
    badges: ["available", "fast-responder", "showreel-verified", "international"],
    responseHours: 3,
    projects: 31,
    endorsements: 14,
    avatarGradient: G.violetDream,
  },
  {
    id: "t-004",
    slug: "sofia-marquez",
    name: "Sofía Márquez",
    handle: "@sofiam",
    initials: "SM",
    countryCode: "ES",
    city: "Barcelona",
    discipline: "vfx",
    specialties: ["FX Sims", "Pyro & Destruction", "Compositing"],
    yearsExperience: 7,
    software: ["Houdini", "Nuke", "Maya", "Substance Painter"],
    languages: ["Spanish", "English", "Catalan"],
    workMode: "hybrid",
    contractType: "studio",
    availability: "on-mission",
    availabilityNote: "On mission until September 2026",
    bio: "FX TD with a soft spot for explosions that read in a single frame.",
    tagline: "Sims that read in a single frame.",
    links: { artstation: "https://artstation.com/sofiam" },
    portfolio: port([
      { kind: "video", title: "Pyro Library Vol. III", gradient: G.magmaRed, ratio: "16/9" },
      { kind: "image", title: "Destruction R&D", gradient: G.goldNoir, ratio: "4/5" },
      { kind: "image", title: "Smoke Plate 12", gradient: G.steelBlue, ratio: "16/9" },
    ]),
    experiences: [
      { studio: "ILM London", role: "FX TD", period: "2022 – Present" },
      { studio: "DNEG Montréal", role: "FX Artist", period: "2019 – 2022" },
    ],
    score: 91,
    percentile: 3,
    globalRank: 88,
    disciplineRank: 12,
    countryRank: 2,
    badges: ["senior", "showreel-verified", "international", "recently-hired"],
    responseHours: 8,
    projects: 28,
    endorsements: 27,
    avatarGradient: G.magmaRed,
  },
  {
    id: "t-005",
    slug: "akira-tanaka",
    name: "Akira Tanaka",
    handle: "@akiratan",
    initials: "AT",
    countryCode: "JP",
    city: "Tokyo",
    discipline: "character-art",
    specialties: ["Stylized Characters", "Grooming", "Look-dev"],
    yearsExperience: 9,
    software: ["ZBrush", "Maya", "Substance Painter", "Marvelous Designer", "Marmoset Toolbag"],
    languages: ["Japanese", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Character artist between film and games, focused on stylized realism.",
    tagline: "Stylized realism, skin that breathes.",
    links: { artstation: "https://artstation.com/akiratan" },
    portfolio: port([
      { kind: "image", title: "Ronin — Hero Bust", gradient: G.amberSun, ratio: "4/5" },
      { kind: "image", title: "Creature Study 04", gradient: G.emeraldDeep, ratio: "1/1" },
      { kind: "image", title: "Lighting Sphere", gradient: G.goldNoir, ratio: "16/9" },
    ]),
    experiences: [
      { studio: "Square Enix", role: "Senior Character Artist", period: "2020 – Present" },
      { studio: "Marza Animation Planet", role: "Character Artist", period: "2016 – 2020" },
    ],
    score: 93,
    percentile: 2,
    globalRank: 32,
    disciplineRank: 5,
    countryRank: 2,
    badges: ["senior", "top10", "showreel-verified", "in-demand", "international"],
    responseHours: 6,
    projects: 52,
    endorsements: 44,
    avatarGradient: G.amberSun,
  },
  {
    id: "t-006",
    slug: "elena-petrova",
    name: "Elena Petrova",
    handle: "@elenap",
    initials: "EP",
    // Lives in Germany, Ukrainian nationality.
    countryCode: "DE",
    nationalityCode: "UA",
    city: "Berlin",
    discipline: "environment-art",
    specialties: ["Modular Kits", "Lighting", "World Building"],
    yearsExperience: 6,
    software: ["Unreal Engine", "Maya", "Substance Designer", "ZBrush"],
    languages: ["Ukrainian", "English", "German"],
    workMode: "remote",
    contractType: "studio",
    availability: "open",
    availabilityNote: "Listening to senior offers",
    bio: "Environment artist with a passion for moody, lived-in cinematic worlds.",
    tagline: "Cinematic worlds, lived-in light.",
    links: { artstation: "https://artstation.com/elenap" },
    portfolio: port([
      { kind: "image", title: "Lost Embassy", gradient: G.steelBlue, ratio: "16/9" },
      { kind: "image", title: "Night Market — Hall 03", gradient: G.roseDusk, ratio: "4/5" },
      { kind: "image", title: "Brutalist Plaza", gradient: G.cyanOcean, ratio: "1/1" },
    ]),
    experiences: [
      { studio: "4A Games", role: "Senior Environment Artist", period: "2021 – Present" },
      { studio: "GSC Game World", role: "Environment Artist", period: "2018 – 2021" },
    ],
    score: 87,
    percentile: 6,
    globalRank: 224,
    disciplineRank: 19,
    countryRank: 1,
    badges: ["showreel-verified", "international", "senior"],
    responseHours: 12,
    projects: 22,
    endorsements: 21,
    avatarGradient: G.steelBlue,
  },
  {
    id: "t-007",
    slug: "mateo-silva",
    name: "Mateo Silva",
    handle: "@matsilva",
    initials: "MS",
    countryCode: "BR",
    city: "São Paulo",
    discipline: "animation-3d",
    specialties: ["Character Animation", "Acting", "Crowds"],
    yearsExperience: 4,
    software: ["Maya", "Blender", "Substance Painter"],
    languages: ["Portuguese", "Spanish", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Character animator focused on subtle, performance-driven acting.",
    tagline: "Subtle performance over big poses.",
    links: { vimeo: "https://vimeo.com/matsilva" },
    portfolio: port([
      { kind: "video", title: "Acting Reel 2026", gradient: G.amberSun, ratio: "16/9" },
      { kind: "video", title: "Dialogue Test — Maya", gradient: G.cyanOcean, ratio: "16/9" },
      { kind: "image", title: "Pose Study", gradient: G.violetDream, ratio: "4/5" },
    ]),
    experiences: [
      { studio: "Birdo Studio", role: "Character Animator", period: "2022 – Present" },
      { studio: "Vetor Zero", role: "Junior Animator", period: "2020 – 2022" },
    ],
    score: 79,
    percentile: 14,
    globalRank: 1102,
    disciplineRank: 88,
    countryRank: 4,
    badges: ["available", "fast-responder", "showreel-verified"],
    responseHours: 2,
    projects: 17,
    endorsements: 11,
    avatarGradient: G.amberSun,
    trending: true,
  },
  {
    id: "t-008",
    slug: "noa-bensaid",
    name: "Noa Ben Saïd",
    handle: "@noabs",
    initials: "NB",
    countryCode: "MA",
    city: "Casablanca",
    discipline: "storyboard",
    specialties: ["Feature Film", "Pre-vis", "Action Sequences"],
    yearsExperience: 7,
    software: ["Photoshop", "Toon Boom", "Procreate"],
    languages: ["French", "Arabic", "English"],
    workMode: "hybrid",
    contractType: "freelance",
    availability: "available",
    bio: "Storyboarder with a strong shot-language background in action and drama.",
    tagline: "Shots that already know how to be cut.",
    links: { website: "https://noabensaid.com" },
    portfolio: port([
      { kind: "image", title: "Action Sequence — Reel", gradient: G.goldNoir, ratio: "16/9" },
      { kind: "image", title: "Pre-vis — Pursuit", gradient: G.steelBlue, ratio: "4/5" },
    ]),
    experiences: [
      { studio: "Ali n' Productions", role: "Lead Storyboard", period: "2021 – Present" },
    ],
    score: 82,
    percentile: 10,
    globalRank: 880,
    disciplineRank: 41,
    countryRank: 1,
    badges: ["available", "international", "showreel-verified"],
    responseHours: 5,
    projects: 14,
    endorsements: 9,
    avatarGradient: G.goldNoir,
  },
  {
    id: "t-009",
    slug: "ines-laurent",
    name: "Inès Laurent",
    handle: "@ineslaurent",
    initials: "IL",
    countryCode: "FR",
    city: "Paris",
    discipline: "visual-direction",
    specialties: ["Art Direction", "Pitch Films", "Brand Worlds"],
    yearsExperience: 10,
    software: ["After Effects", "Cinema 4D", "Photoshop", "Illustrator"],
    languages: ["French", "English"],
    workMode: "hybrid",
    contractType: "any",
    availability: "open",
    bio: "Visual director shaping language for premium brands and film projects.",
    tagline: "Direction first. Pixels follow.",
    links: { website: "https://ines.studio" },
    portfolio: port([
      { kind: "image", title: "Maison — Lookbook", gradient: G.roseDusk, ratio: "4/5" },
      { kind: "image", title: "Pitch Film — Aether", gradient: G.cyanOcean, ratio: "16/9" },
      { kind: "image", title: "Editorial Frame 07", gradient: G.goldNoir, ratio: "1/1" },
    ]),
    experiences: [
      { studio: "BETC", role: "Art Director", period: "2019 – Present" },
      { studio: "Publicis", role: "Senior Designer", period: "2016 – 2019" },
    ],
    score: 90,
    percentile: 4,
    globalRank: 142,
    disciplineRank: 9,
    countryRank: 2,
    badges: ["senior", "top10", "visual-storytelling", "international"],
    responseHours: 9,
    projects: 38,
    endorsements: 33,
    avatarGradient: G.roseDusk,
  },
  {
    id: "t-010",
    slug: "henry-okafor",
    name: "Henry Okafor",
    handle: "@henryok",
    initials: "HO",
    countryCode: "GB",
    city: "London",
    discipline: "unreal",
    specialties: ["LED Volumes", "Cinematics", "Look-dev"],
    yearsExperience: 6,
    software: ["Unreal Engine", "Maya", "Substance Painter", "Nuke"],
    languages: ["English"],
    workMode: "onsite",
    contractType: "fulltime",
    availability: "open",
    bio: "Unreal artist between commercials and high-end virtual production.",
    tagline: "Camera-ready Unreal cinematics.",
    links: { artstation: "https://artstation.com/henryok" },
    portfolio: port([
      { kind: "video", title: "Volume Test 06", gradient: G.amberSun, ratio: "16/9" },
      { kind: "image", title: "Cinematic Frame — Stack", gradient: G.steelBlue, ratio: "4/5" },
    ]),
    experiences: [
      { studio: "Framestore", role: "Unreal Artist", period: "2022 – Present" },
      { studio: "MPC", role: "Junior Artist", period: "2019 – 2022" },
    ],
    score: 86,
    percentile: 7,
    globalRank: 318,
    disciplineRank: 22,
    countryRank: 4,
    badges: ["unreal-specialist", "showreel-verified", "international"],
    responseHours: 10,
    projects: 18,
    endorsements: 16,
    avatarGradient: G.amberSun,
  },
  {
    id: "t-011",
    slug: "amelie-roy",
    name: "Amélie Roy",
    handle: "@amelier",
    initials: "AR",
    countryCode: "CA",
    city: "Montréal",
    discipline: "animation-3d",
    specialties: ["Creature Animation", "Feature Film"],
    yearsExperience: 11,
    software: ["Maya", "ZBrush", "Houdini"],
    languages: ["French", "English"],
    workMode: "hybrid",
    contractType: "studio",
    availability: "on-mission",
    availabilityNote: "On mission until July 2026",
    bio: "Senior creature animator across feature pipelines.",
    tagline: "Creatures that earn their weight.",
    links: { artstation: "https://artstation.com/amelier" },
    portfolio: port([
      { kind: "video", title: "Creature Reel — 2025", gradient: G.emeraldDeep, ratio: "16/9" },
    ]),
    experiences: [
      { studio: "Rodeo FX", role: "Senior Animator", period: "2018 – Present" },
    ],
    score: 92,
    percentile: 3,
    globalRank: 64,
    disciplineRank: 7,
    countryRank: 1,
    badges: ["senior", "top10", "recently-hired", "showreel-verified"],
    responseHours: 16,
    projects: 46,
    endorsements: 41,
    avatarGradient: G.emeraldDeep,
  },
  {
    id: "t-012",
    slug: "rohan-iyer",
    name: "Rohan Iyer",
    handle: "@rohaniyer",
    initials: "RI",
    countryCode: "IN",
    city: "Mumbai",
    discipline: "vfx",
    specialties: ["Compositing", "DMP Integration", "Roto / Paint"],
    yearsExperience: 5,
    software: ["Nuke", "Maya", "Photoshop"],
    languages: ["English", "Hindi"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Senior compositor with feature credits across Marvel and Netflix shows.",
    tagline: "Comps that hide the work.",
    links: { artstation: "https://artstation.com/rohani" },
    portfolio: port([
      { kind: "video", title: "Comp Reel — 2026", gradient: G.steelBlue, ratio: "16/9" },
      { kind: "image", title: "Plate vs Final", gradient: G.violetDream, ratio: "16/9" },
    ]),
    experiences: [
      { studio: "DNEG India", role: "Senior Compositor", period: "2022 – Present" },
    ],
    score: 83,
    percentile: 9,
    globalRank: 702,
    disciplineRank: 51,
    countryRank: 2,
    badges: ["available", "fast-responder", "showreel-verified"],
    responseHours: 3,
    projects: 24,
    endorsements: 12,
    avatarGradient: G.violetDream,
  },
  {
    id: "t-013",
    slug: "yuki-shibata",
    name: "Yuki Shibata",
    handle: "@yukishibata",
    initials: "YS",
    countryCode: "JP",
    city: "Kyoto",
    discipline: "motion-design",
    professionId: "frontend-engineer",
    specialties: ["React", "TypeScript", "Design Systems"],
    yearsExperience: 4,
    software: ["Figma", "After Effects"],
    languages: ["Japanese", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    remoteOnly: true,
    bio: "Frontend engineer between product design and engineering — design systems, motion in UI.",
    tagline: "Design-eng hybrid. Tokens to motion.",
    links: { website: "https://yukis.dev" },
    portfolio: port([
      { kind: "image", title: "Design system — Aurora", gradient: G.cyanOcean, ratio: "16/9" },
      { kind: "image", title: "Editor UI — Studio", gradient: G.amberSun, ratio: "1/1" },
    ]),
    experiences: [{ studio: "Linear", role: "Frontend Engineer", period: "2022 – Present" }],
    score: 78,
    percentile: 16,
    globalRank: 1340,
    disciplineRank: 102,
    countryRank: 12,
    badges: ["available", "fast-responder"],
    responseHours: 2,
    projects: 12,
    endorsements: 6,
    avatarGradient: G.cyanOcean,
    trending: true,
  },
  {
    id: "t-014",
    slug: "marcus-weiss",
    name: "Marcus Weiss",
    handle: "@marcusw",
    initials: "MW",
    countryCode: "DE",
    city: "Berlin",
    discipline: "editing",
    professionId: "data-scientist",
    specialties: ["Forecasting", "Time-Series", "Causal Inference"],
    yearsExperience: 12,
    software: ["Photoshop"],
    languages: ["German", "English"],
    workMode: "hybrid",
    contractType: "freelance",
    availability: "open",
    freelanceOnly: true,
    bio: "Senior data scientist between fintech and energy. Bayesian + causal toolkit.",
    tagline: "Forecasts that hold up to a board meeting.",
    links: { website: "https://marcusw.io" },
    portfolio: port([
      { kind: "image", title: "Forecast — Energy demand", gradient: G.steelBlue, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Independent", role: "Principal Data Scientist", period: "2014 – Present" }],
    score: 85,
    percentile: 8,
    globalRank: 410,
    disciplineRank: 28,
    countryRank: 3,
    badges: ["senior", "international"],
    responseHours: 14,
    projects: 64,
    endorsements: 25,
    avatarGradient: G.steelBlue,
  },
  {
    id: "t-015",
    slug: "diana-popescu",
    name: "Diana Popescu",
    handle: "@dianap",
    initials: "DP",
    countryCode: "FR",
    city: "Lyon",
    discipline: "generalist-3d",
    specialties: ["Cinematics", "Look-dev", "Lighting"],
    yearsExperience: 5,
    software: ["Blender", "Substance Painter", "Unreal Engine"],
    languages: ["French", "Romanian", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Generalist with a sharp lighting eye, Blender-first pipeline.",
    tagline: "Blender-first, light-led.",
    links: { artstation: "https://artstation.com/dianap" },
    portfolio: port([
      { kind: "image", title: "Lighting Frame — Atrium", gradient: G.amberSun, ratio: "16/9" },
      { kind: "image", title: "Glass Study", gradient: G.cyanOcean, ratio: "4/5" },
    ]),
    experiences: [{ studio: "Freelance", role: "3D Generalist", period: "2021 – Present" }],
    score: 80,
    percentile: 12,
    globalRank: 980,
    disciplineRank: 73,
    countryRank: 14,
    badges: ["available", "fast-responder", "showreel-verified"],
    responseHours: 3,
    projects: 19,
    endorsements: 10,
    avatarGradient: G.amberSun,
    recentlyJoined: true,
  },
  {
    id: "t-016",
    slug: "tomas-novak",
    name: "Tomas Novak",
    handle: "@tnovak",
    initials: "TN",
    countryCode: "PL",
    city: "Warsaw",
    discipline: "environment-art",
    specialties: ["Procedural Worlds", "Substance Designer", "Materials"],
    yearsExperience: 8,
    software: ["Substance Designer", "Maya", "Houdini", "Unreal Engine"],
    languages: ["Polish", "English"],
    workMode: "remote",
    contractType: "fulltime",
    availability: "open",
    bio: "Procedural material specialist for AAA worlds.",
    tagline: "Materials that scale.",
    links: { artstation: "https://artstation.com/tnovak" },
    portfolio: port([
      { kind: "image", title: "Material Pack — Stone", gradient: G.goldNoir, ratio: "1/1" },
      { kind: "image", title: "World Slice 04", gradient: G.emeraldDeep, ratio: "16/9" },
    ]),
    experiences: [{ studio: "CD Projekt RED", role: "Senior Material Artist", period: "2019 – Present" }],
    score: 89,
    percentile: 5,
    globalRank: 198,
    disciplineRank: 14,
    countryRank: 1,
    badges: ["senior", "showreel-verified", "in-demand"],
    responseHours: 11,
    projects: 33,
    endorsements: 22,
    avatarGradient: G.goldNoir,
  },
  {
    id: "t-017",
    slug: "isla-thompson",
    name: "Isla Thompson",
    handle: "@islath",
    initials: "IT",
    countryCode: "GB",
    city: "Bristol",
    discipline: "character-art",
    specialties: ["Stylized", "Game Characters", "Hair & Cloth"],
    yearsExperience: 6,
    software: ["ZBrush", "Marvelous Designer", "Substance Painter", "Maya"],
    languages: ["English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Character artist for indie and AA titles.",
    tagline: "Stylized characters that ship.",
    links: { artstation: "https://artstation.com/islath" },
    portfolio: port([
      { kind: "image", title: "Pirate Bust", gradient: G.roseDusk, ratio: "4/5" },
      { kind: "image", title: "Cloth Test 02", gradient: G.amberSun, ratio: "1/1" },
    ]),
    experiences: [{ studio: "Aardman", role: "Character Artist", period: "2022 – Present" }],
    score: 81,
    percentile: 11,
    globalRank: 902,
    disciplineRank: 64,
    countryRank: 14,
    badges: ["available", "fast-responder", "showreel-verified"],
    responseHours: 4,
    projects: 21,
    endorsements: 13,
    avatarGradient: G.roseDusk,
  },
  {
    id: "t-018",
    slug: "andre-silva",
    name: "André Silva",
    handle: "@andresilva",
    initials: "AS",
    countryCode: "PT",
    city: "Lisbon",
    discipline: "vfx",
    specialties: ["Houdini FX", "Water", "Smoke"],
    yearsExperience: 4,
    software: ["Houdini", "Nuke", "Mantra", "Karma"],
    languages: ["Portuguese", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Houdini FX artist focused on water and smoke.",
    tagline: "Water that wants to be cinema.",
    links: { artstation: "https://artstation.com/andresilva" },
    portfolio: port([
      { kind: "video", title: "Water Sim — Beach", gradient: G.steelBlue, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Independent", role: "FX Artist", period: "2022 – Present" }],
    score: 77,
    percentile: 18,
    globalRank: 1480,
    disciplineRank: 112,
    countryRank: 2,
    badges: ["available", "fast-responder"],
    responseHours: 4,
    projects: 9,
    endorsements: 4,
    avatarGradient: G.steelBlue,
    recentlyJoined: true,
    trending: true,
  },
  {
    id: "t-019",
    slug: "maya-cohen",
    name: "Maya Cohen",
    handle: "@mayacohen",
    initials: "MC",
    countryCode: "US",
    city: "Los Angeles",
    discipline: "animation-3d",
    specialties: ["Acting Animation", "Game Cinematics"],
    yearsExperience: 9,
    software: ["Maya", "MotionBuilder", "Unreal Engine"],
    languages: ["English"],
    workMode: "hybrid",
    contractType: "fulltime",
    availability: "on-mission",
    availabilityNote: "On mission until November 2026",
    bio: "Senior animator with cinematic credits across AAA games.",
    tagline: "Performance-first animation.",
    links: { artstation: "https://artstation.com/mayacohen" },
    portfolio: port([
      { kind: "video", title: "Acting Cinematic Reel", gradient: G.amberSun, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Naughty Dog", role: "Senior Animator", period: "2020 – Present" }],
    score: 93,
    percentile: 2,
    globalRank: 28,
    disciplineRank: 3,
    countryRank: 6,
    badges: ["senior", "top10", "recently-hired", "showreel-verified", "visual-storytelling"],
    responseHours: 18,
    projects: 38,
    endorsements: 51,
    avatarGradient: G.amberSun,
  },
  {
    id: "t-020",
    slug: "lukas-eriksson",
    name: "Lukas Eriksson",
    handle: "@lukase",
    initials: "LE",
    countryCode: "SE",
    city: "Stockholm",
    discipline: "unreal",
    specialties: ["Niagara FX", "Real-time Cinematics", "Tooling"],
    yearsExperience: 7,
    software: ["Unreal Engine", "Houdini", "Maya"],
    languages: ["Swedish", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Unreal artist with TD chops. Niagara obsessive.",
    tagline: "Real-time FX with TD eyes.",
    links: { artstation: "https://artstation.com/lukase" },
    portfolio: port([
      { kind: "video", title: "Niagara Reel", gradient: G.cyanOcean, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Embark", role: "Senior Tech Artist", period: "2021 – Present" }],
    score: 90,
    percentile: 4,
    globalRank: 138,
    disciplineRank: 11,
    countryRank: 1,
    badges: ["unreal-specialist", "showreel-verified", "in-demand", "available"],
    responseHours: 5,
    projects: 26,
    endorsements: 28,
    avatarGradient: G.cyanOcean,
  },
  {
    id: "t-021",
    slug: "ana-rodriguez",
    name: "Ana Rodríguez",
    handle: "@anaro",
    initials: "AR",
    countryCode: "MX",
    city: "Mexico City",
    discipline: "motion-design",
    professionId: "growth-marketer",
    specialties: ["Paid Acquisition", "Funnels", "B2C SaaS"],
    yearsExperience: 5,
    software: ["Photoshop", "Figma"],
    languages: ["Spanish", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    remoteOnly: true,
    bio: "Growth marketer with hands-on paid + funnel chops for B2C SaaS.",
    tagline: "Paid + funnel + retention. All three.",
    links: { website: "https://anaro.work" },
    portfolio: port([
      { kind: "image", title: "Funnel teardown — Notion", gradient: G.roseDusk, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Independent", role: "Growth Lead", period: "2020 – Present" }],
    score: 82,
    percentile: 10,
    globalRank: 720,
    disciplineRank: 53,
    countryRank: 1,
    badges: ["available", "fast-responder", "international"],
    responseHours: 2,
    projects: 28,
    endorsements: 17,
    avatarGradient: G.roseDusk,
  },
  {
    id: "t-022",
    slug: "yara-nahas",
    name: "Yara Nahas",
    handle: "@yaran",
    initials: "YN",
    countryCode: "EG",
    city: "Cairo",
    discipline: "storyboard",
    specialties: ["Animation Features", "Series", "Pre-vis"],
    yearsExperience: 6,
    software: ["Toon Boom", "Procreate", "Photoshop"],
    languages: ["Arabic", "English", "French"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Storyboarder across animation series and feature pre-vis.",
    tagline: "Storyboards that already feel cut.",
    links: { website: "https://yaran.studio" },
    portfolio: port([
      { kind: "image", title: "Feature Pre-vis", gradient: G.amberSun, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Freelance", role: "Storyboard", period: "2020 – Present" }],
    score: 79,
    percentile: 15,
    globalRank: 1280,
    disciplineRank: 78,
    countryRank: 1,
    badges: ["available", "fast-responder", "international"],
    responseHours: 3,
    projects: 14,
    endorsements: 8,
    avatarGradient: G.amberSun,
    recentlyJoined: true,
  },
  {
    id: "t-023",
    slug: "victor-chen",
    name: "Victor Chen",
    handle: "@victorc",
    initials: "VC",
    countryCode: "CN",
    city: "Shanghai",
    discipline: "environment-art",
    specialties: ["Cinematic Environments", "Photogrammetry"],
    yearsExperience: 9,
    software: ["Unreal Engine", "Maya", "RealityCapture", "Substance Designer"],
    languages: ["Mandarin", "English"],
    workMode: "onsite",
    contractType: "fulltime",
    availability: "on-mission",
    bio: "Cinematic environment lead. Photogrammetry-first pipelines.",
    tagline: "Worlds scanned from real ones.",
    links: { artstation: "https://artstation.com/victorc" },
    portfolio: port([
      { kind: "image", title: "Capture Lab — Cathedral", gradient: G.goldNoir, ratio: "16/9" },
    ]),
    experiences: [{ studio: "miHoYo", role: "Lead Environment Artist", period: "2020 – Present" }],
    score: 91,
    percentile: 3,
    globalRank: 92,
    disciplineRank: 8,
    countryRank: 2,
    badges: ["senior", "top10", "recently-hired", "showreel-verified"],
    responseHours: 22,
    projects: 31,
    endorsements: 36,
    avatarGradient: G.goldNoir,
  },
  {
    id: "t-024",
    slug: "olivia-andersson",
    name: "Olivia Andersson",
    handle: "@oliviaa",
    initials: "OA",
    countryCode: "NO",
    city: "Oslo",
    discipline: "visual-direction",
    professionId: "product-designer",
    specialties: ["Product Design", "Design Systems", "Editorial UI"],
    yearsExperience: 8,
    software: ["Figma", "After Effects"],
    languages: ["Norwegian", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Product designer with an editorial Nordic vocabulary.",
    tagline: "Editorial silence over loud product.",
    links: { website: "https://oliviaa.work" },
    portfolio: port([
      { kind: "image", title: "Lookbook — Atelier", gradient: G.steelBlue, ratio: "4/5" },
    ]),
    experiences: [{ studio: "Freelance", role: "Visual Director", period: "2018 – Present" }],
    score: 86,
    percentile: 7,
    globalRank: 320,
    disciplineRank: 22,
    countryRank: 1,
    badges: ["senior", "showreel-verified", "available"],
    responseHours: 6,
    projects: 22,
    endorsements: 18,
    avatarGradient: G.steelBlue,
  },
  {
    id: "t-025",
    slug: "ibrahim-keita",
    name: "Ibrahim Keïta",
    handle: "@ibrahimk",
    initials: "IK",
    countryCode: "CM",
    city: "Douala",
    discipline: "animation-3d",
    specialties: ["Character Animation", "Stylized"],
    yearsExperience: 3,
    software: ["Blender", "Maya"],
    languages: ["French", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Rising character animator with stylized acting reel.",
    tagline: "Stylized acting, rising fast.",
    links: { vimeo: "https://vimeo.com/ibrahimk" },
    portfolio: port([
      { kind: "video", title: "Acting Reel 2025", gradient: G.amberSun, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Freelance", role: "Animator", period: "2023 – Present" }],
    score: 74,
    percentile: 22,
    globalRank: 1820,
    disciplineRank: 142,
    countryRank: 2,
    badges: ["available", "fast-responder", "showreel-verified"],
    responseHours: 2,
    projects: 7,
    endorsements: 3,
    avatarGradient: G.amberSun,
    recentlyJoined: true,
    trending: true,
  },
  {
    id: "t-026",
    slug: "claire-dupont",
    name: "Claire Dupont",
    handle: "@claired",
    initials: "CD",
    countryCode: "FR",
    city: "Annecy",
    discipline: "editing",
    professionId: "financial-analyst",
    specialties: ["FP&A", "Modeling", "M&A diligence"],
    yearsExperience: 11,
    software: ["Photoshop"],
    languages: ["French", "English"],
    workMode: "hybrid",
    contractType: "studio",
    availability: "open",
    bio: "Senior FP&A with M&A diligence experience across European tech.",
    tagline: "Models that hold up to a Series-B board.",
    links: { website: "https://claired.fi" },
    portfolio: port([
      { kind: "image", title: "Three-statement model — Showcase", gradient: G.goldNoir, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Independent", role: "Senior FP&A", period: "2018 – Present" }],
    score: 87,
    percentile: 6,
    globalRank: 280,
    disciplineRank: 18,
    countryRank: 2,
    badges: ["senior", "international"],
    responseHours: 14,
    projects: 47,
    endorsements: 30,
    avatarGradient: G.goldNoir,
  },
  {
    id: "t-027",
    slug: "haruto-mori",
    name: "Haruto Mori",
    handle: "@harutom",
    initials: "HM",
    countryCode: "JP",
    city: "Osaka",
    discipline: "character-art",
    professionId: "music-producer",
    specialties: ["Mixing", "Sound Design", "Film Score"],
    yearsExperience: 7,
    software: ["Photoshop"],
    languages: ["Japanese", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Music producer & sound designer between film score and ambient electronica.",
    tagline: "Hyper-detail sound. With restraint.",
    links: { website: "https://harutom.audio" },
    portfolio: port([
      { kind: "image", title: "Hero Bust — Stoic", gradient: G.steelBlue, ratio: "4/5" },
    ]),
    experiences: [{ studio: "Polyphony Digital", role: "Character Artist", period: "2020 – Present" }],
    score: 89,
    percentile: 5,
    globalRank: 162,
    disciplineRank: 12,
    countryRank: 4,
    badges: ["senior", "showreel-verified", "available", "international"],
    responseHours: 6,
    projects: 24,
    endorsements: 23,
    avatarGradient: G.steelBlue,
  },
  {
    id: "t-028",
    slug: "linnea-holm",
    name: "Linnea Holm",
    handle: "@linneah",
    initials: "LH",
    countryCode: "FI",
    city: "Helsinki",
    discipline: "vfx",
    specialties: ["Smoke", "Pyro", "Dust"],
    yearsExperience: 6,
    software: ["Houdini", "Nuke"],
    languages: ["Finnish", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "open",
    bio: "FX artist focused on atmospherics.",
    tagline: "Atmospherics with weight.",
    links: { artstation: "https://artstation.com/linneah" },
    portfolio: port([
      { kind: "video", title: "Atmos Reel", gradient: G.violetDream, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Remedy Entertainment", role: "FX Artist", period: "2021 – Present" }],
    score: 84,
    percentile: 8,
    globalRank: 460,
    disciplineRank: 30,
    countryRank: 1,
    badges: ["senior", "showreel-verified", "in-demand"],
    responseHours: 8,
    projects: 19,
    endorsements: 16,
    avatarGradient: G.violetDream,
  },
  {
    id: "t-029",
    slug: "diego-fernandez",
    name: "Diego Fernández",
    handle: "@diegof",
    initials: "DF",
    countryCode: "AR",
    city: "Buenos Aires",
    discipline: "generalist-3d",
    specialties: ["Look-dev", "Lighting", "Compositing"],
    yearsExperience: 7,
    software: ["Blender", "Cycles", "Nuke", "Photoshop"],
    languages: ["Spanish", "English"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Generalist with feature credits in cinematic short films.",
    tagline: "Generalist with a colorist's eye.",
    links: { artstation: "https://artstation.com/diegof" },
    portfolio: port([
      { kind: "image", title: "Short Film — Bell", gradient: G.amberSun, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Freelance", role: "Generalist", period: "2018 – Present" }],
    score: 83,
    percentile: 9,
    globalRank: 640,
    disciplineRank: 44,
    countryRank: 1,
    badges: ["showreel-verified", "available", "international"],
    responseHours: 5,
    projects: 26,
    endorsements: 15,
    avatarGradient: G.amberSun,
  },
  {
    id: "t-030",
    slug: "samuel-okeke",
    name: "Samuel Okeke",
    handle: "@samok",
    initials: "SO",
    countryCode: "KE",
    city: "Nairobi",
    discipline: "unreal",
    specialties: ["Architectural Visualization", "Cinematics"],
    yearsExperience: 4,
    software: ["Unreal Engine", "Twinmotion", "Blender"],
    languages: ["English", "Swahili"],
    workMode: "remote",
    contractType: "freelance",
    availability: "available",
    bio: "Unreal artist between archviz and cinematic short-form.",
    tagline: "Archviz that doesn't look like archviz.",
    links: { artstation: "https://artstation.com/samok" },
    portfolio: port([
      { kind: "image", title: "Lobby — Lumen Test", gradient: G.cyanOcean, ratio: "16/9" },
      { kind: "video", title: "Atrium Walkthrough", gradient: G.goldNoir, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Freelance", role: "Unreal Artist", period: "2022 – Present" }],
    score: 76,
    percentile: 19,
    globalRank: 1560,
    disciplineRank: 96,
    countryRank: 1,
    badges: ["available", "fast-responder", "showreel-verified"],
    responseHours: 3,
    projects: 11,
    endorsements: 5,
    avatarGradient: G.cyanOcean,
    recentlyJoined: true,
  },
  // ── Cross-sector additions (Sprint 2 vision pivot) ──
  {
    id: "t-031",
    slug: "marina-okafor",
    name: "Marina Okafor",
    handle: "@marinaok",
    initials: "MO",
    countryCode: "NG",
    city: "Lagos",
    discipline: "generalist-3d",
    professionId: "software-engineer",
    specialties: ["Distributed Systems", "Rust", "Go"],
    yearsExperience: 7,
    software: ["Photoshop"],
    languages: ["English", "Yoruba"],
    workMode: "remote",
    contractType: "fulltime",
    availability: "open",
    remoteOnly: true,
    availableInDays: 60,
    bio: "Backend engineer building distributed systems for fintech. Rust + Go shop.",
    tagline: "Backends that scale before they need to.",
    links: { website: "https://marina.dev" },
    portfolio: port([
      { kind: "image", title: "Architecture — Payments switch", gradient: G.cyanOcean, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Flutterwave", role: "Senior Backend Engineer", period: "2021 – Present" }],
    score: 86,
    percentile: 6,
    globalRank: 308,
    disciplineRank: 14,
    countryRank: 1,
    badges: ["senior", "international", "fast-responder"],
    responseHours: 4,
    projects: 22,
    endorsements: 19,
    avatarGradient: G.cyanOcean,
  },
  {
    id: "t-032",
    slug: "amir-haddad",
    name: "Amir Haddad",
    handle: "@amirh",
    initials: "AH",
    countryCode: "FR",
    city: "Paris",
    discipline: "generalist-3d",
    professionId: "ml-engineer",
    specialties: ["LLM Eval", "RAG Systems", "Vector DBs"],
    yearsExperience: 5,
    software: ["Photoshop"],
    languages: ["French", "English", "Arabic"],
    workMode: "hybrid",
    contractType: "fulltime",
    availability: "available",
    availableInDays: 30,
    bio: "ML engineer focused on production LLM evaluation and retrieval systems.",
    tagline: "LLM systems that you can actually monitor.",
    links: { website: "https://amirh.dev" },
    portfolio: port([
      { kind: "image", title: "RAG eval framework — Demo", gradient: G.violetDream, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Mistral AI", role: "Applied ML Engineer", period: "2023 – Present" }],
    score: 89,
    percentile: 5,
    globalRank: 174,
    disciplineRank: 6,
    countryRank: 3,
    badges: ["available", "in-demand", "fast-responder", "international"],
    responseHours: 3,
    projects: 14,
    endorsements: 21,
    avatarGradient: G.violetDream,
    trending: true,
  },
  {
    id: "t-033",
    slug: "fatou-diop",
    name: "Fatou Diop",
    handle: "@fatoud",
    initials: "FD",
    countryCode: "FR",
    city: "Toulouse",
    discipline: "generalist-3d",
    professionId: "ux-designer",
    specialties: ["Healthcare UX", "Accessibility", "Service Design"],
    yearsExperience: 6,
    software: ["Figma", "Photoshop"],
    languages: ["French", "English"],
    workMode: "hybrid",
    contractType: "freelance",
    availability: "available",
    freelanceOnly: true,
    bio: "UX designer between healthcare and public-service products. WCAG-first.",
    tagline: "Service design that respects everyone.",
    links: { website: "https://fatou.design" },
    portfolio: port([
      { kind: "image", title: "Patient triage flow — Hospital", gradient: G.roseDusk, ratio: "4/5" },
    ]),
    experiences: [{ studio: "Independent", role: "Senior UX", period: "2020 – Present" }],
    score: 84,
    percentile: 8,
    globalRank: 460,
    disciplineRank: 19,
    countryRank: 6,
    badges: ["available", "fast-responder", "international"],
    responseHours: 5,
    projects: 18,
    endorsements: 14,
    avatarGradient: G.roseDusk,
  },
  {
    id: "t-034",
    slug: "kenji-okuda",
    name: "Kenji Okuda",
    handle: "@kenjio",
    initials: "KO",
    countryCode: "JP",
    city: "Yokohama",
    discipline: "generalist-3d",
    professionId: "architect",
    specialties: ["Civic Architecture", "Timber Construction", "Passive Design"],
    yearsExperience: 11,
    software: ["Photoshop"],
    languages: ["Japanese", "English"],
    workMode: "hybrid",
    contractType: "studio",
    availability: "open",
    bio: "Architect across civic and education projects. Timber-first, passive-energy mindset.",
    tagline: "Architecture that ages well.",
    links: { website: "https://kenji.studio" },
    portfolio: port([
      { kind: "image", title: "Yokohama Library — Concept", gradient: G.goldNoir, ratio: "16/9" },
      { kind: "image", title: "Timber House — Detail", gradient: G.steelBlue, ratio: "4/5" },
    ]),
    experiences: [{ studio: "Kuma & Associates", role: "Senior Architect", period: "2019 – Present" }],
    score: 90,
    percentile: 4,
    globalRank: 158,
    disciplineRank: 4,
    countryRank: 5,
    badges: ["senior", "showreel-verified", "international"],
    responseHours: 18,
    projects: 27,
    endorsements: 24,
    avatarGradient: G.goldNoir,
  },
  {
    id: "t-035",
    slug: "lea-nguyen",
    name: "Léa Nguyen",
    handle: "@lean",
    initials: "LN",
    countryCode: "FR",
    nationalityCode: "VN",
    city: "Bordeaux",
    discipline: "generalist-3d",
    professionId: "medical-doctor",
    specialties: ["Telemedicine", "Family Medicine", "Public Health"],
    yearsExperience: 6,
    software: ["Photoshop"],
    languages: ["French", "Vietnamese", "English"],
    workMode: "hybrid",
    contractType: "any",
    availability: "available",
    availableInDays: 45,
    bio: "MD focused on telemedicine and continuity-of-care platforms. Open to product-medical roles.",
    tagline: "Bringing the bedside to the screen.",
    links: { website: "https://lea-md.fr" },
    portfolio: port([
      { kind: "image", title: "Patient pathway — Telemedicine pilot", gradient: G.emeraldDeep, ratio: "16/9" },
    ]),
    experiences: [{ studio: "Doctolib", role: "Medical Advisor (part-time)", period: "2022 – Present" }],
    score: 83,
    percentile: 9,
    globalRank: 620,
    disciplineRank: 22,
    countryRank: 8,
    badges: ["available", "international"],
    responseHours: 6,
    projects: 12,
    endorsements: 11,
    avatarGradient: G.emeraldDeep,
    recentlyJoined: true,
  },
];

export function getTalent(slug: string): Talent | undefined {
  return TALENTS.find((t) => t.slug === slug);
}

export function getTopTalents(n: number = 10): Talent[] {
  return [...TALENTS].sort((a, b) => b.score - a.score).slice(0, n);
}

export function getTrendingTalents(n: number = 6): Talent[] {
  return TALENTS.filter((t) => t.trending).slice(0, n);
}

export function getAvailableTalents(): Talent[] {
  return TALENTS.filter((t) => t.availability === "available");
}

export function getTalentTier(t: Talent) {
  return tierForPercentile(t.percentile);
}

// ────────────────────────────────────────────────────────────────────────────
// Profession-first resolution helpers
// ────────────────────────────────────────────────────────────────────────────
// CRITICAL CONTRACT: every talent in TalentRank belongs to exactly ONE
// profession. The canonical answer is `professionId`. If a record only has the
// legacy `discipline` field, we resolve it through DISCIPLINE_TO_PROFESSION.
// All rankings, marquees, filters, and UI MUST go through these helpers so
// professions never get mixed.

/** Resolve the canonical profession id for a talent. Always returns a string —
 *  falls back to "other" for any record that can't be resolved. */
export function talentProfessionId(t: Talent): string {
  return t.professionId ?? DISCIPLINE_TO_PROFESSION[t.discipline] ?? "other";
}

/** Resolve the full Profession record for a talent. */
export function getTalentProfession(t: Talent): Profession {
  const id = talentProfessionId(t);
  return getProfession(id) ?? getProfession("other")!;
}

/** Strict filter: only talents whose canonical profession === `professionId`. */
export function getTalentsByProfession(professionId: string): Talent[] {
  return TALENTS.filter((t) => talentProfessionId(t) === professionId);
}

/** Top N talents within a single profession. Sorted by score desc. */
export function getTopByProfession(professionId: string, n: number = 10): Talent[] {
  return getTalentsByProfession(professionId)
    .sort((a, b) => b.score - a.score)
    .slice(0, n);
}

export type { TierId };
